### ISSUE TITLE
Auth failure after enabling 2FA

### ISSUE THREAD

**Issue by jesperfj** [heroku/legacy-cli#1197]
I performed the following sequence:
1. Logged in with `heroku login` in shell
2. Enable 2FA on dashboard.heroku.com
3. Go back to CLI and type `heroku apps`

At this point I get an auth failure as expected and I am prompted for username, password and 2FA code. Then the CLI prints `Authentication successful.` followed by `Authentication failure.`. I tried a few times again with no success. Then I stopped it `CTRL-C` and ran `heroku login` which succeeded and now it all works. Here's some sample terminal output:

```
hdev@f51524cc34c6:~$ heroku apps       
Authentication failure
Enter your Heroku credentials.
Email: jesperfj@gmail.com
Password (typing will be hidden): 
Two-factor code: 459579
Authentication successful.
Authentication failure
Enter your Heroku credentials.
Email: jesperfj@gmail.com
Password (typing will be hidden): 
Authentication successful.
Authentication failure
Enter your Heroku credentials.
Email: Password (typing will be hidden):  !    Command cancelled.
hdev@f51524cc34c6:~$ 
hdev@f51524cc34c6:~$ cat .netrc 
hdev@f51524cc34c6:~$ heroku login
Enter your Heroku credentials.
Email: jesperfj@gmail.com
Password (typing will be hidden): 
Two-factor code: 684420
Authentication successful.
hdev@f51524cc34c6:~$ 
```

This is using the deb package of toolbelt and runs in an Ubuntu 14.04 docker container.

**Comment by benalavi** [comment]
I had this same issue as well w/ 3.24.4 after enabling 2FA. A fresh install fixed it.

I noticed that if I got my credentials wrong then it wouldn't even get to the 2FA step, and if I typed the token wrong then it would give an error specific to the 2FA token. So it seems like I was successfully authenticating, but still ending up denied.
