### ISSUE TITLE
When I try to scale my dynos, it repeatedly asks me for my email and password

### ISSUE THREAD

**Issue by Tim15** [heroku/legacy-cli#1801]
I `cd` into my repo
I login to heroku with 

```
$ heroku login
Enter your Heroku credentials.
Email: timhigins@gmail.com
Password (typing will be hidden): 
Logged in as timhigins@gmail.com
```

Then I try to scale my app
Here are the logs:

```
$ heroku ps:scale web=1
Scaling dynos... Enter your Heroku credentials.
Email: timhigins@gmail.com
Password (typing will be hidden): 
Logged in as timhigins@gmail.com
Enter your Heroku credentials.
Email: timhigins@gmail.com
Password (typing will be hidden): 
Logged in as timhigins@gmail.com
```

It keeps asking me for my credentials until I control-C stop the proccess.

**Comment by dickeyxxx** [comment]
what is the output of `heroku version`?

**Comment by mountwe** [comment]
Hello, I have the same problem when I download a getting-started directory and do "heroku create"  This is my answer to your question. Note running on WIndows 7 Pro 64-bit.

    heroku/toolbelt/3.42.22 (i386-mingw32) ruby/2.1.7
    heroku-cli/4.27.6-e59743f (386-windows) go1.5.1
    === Installed Plugins
    heroku-apps@0.5.4
    heroku-cli-addons@0.1.1
    heroku-fork@4.0.0
    heroku-git@2.4.3
    heroku-local@4.1.5
    heroku-run@2.9.2
    heroku-status@1.2.3

**Comment by dickeyxxx** [comment]
@ransombriggs is looking to make the parser more liberal in terms of what it takes in, but this likely means you have an invalid netrc file. Try deleting it (maybe want to back it up) and trying again.

**Comment by mountwe** [comment]
@dickeyxxx thanks for the suggestion. I have seen a couple of comments about Windows and netrc. I'll give it a try. It is most frustrating, trying to get ANY of the Heroku intro projects going.

**Comment by panozzaj** [comment]
Thanks for writing up this suggestion! I was running into the same problem for a few hours. I had a line in my `.netrc` that apparently was invalid. After moving it to another location, I didn't encounter the infinite login loop when trying to get the logs. Thanks again!

**Comment by Tim15** [comment]
Some type of issue with `.netrc`, see #1836.
