### ISSUE TITLE
Can't update a plugin

### ISSUE THREAD

**Issue by tnoonan-salesforce** [heroku/legacy-cli#2022]
After installing a plugin using a tag I cannot update it.

Using these commands doesn't result in an update:

heroku plugins:update
heroku plugins:update salesforce-alm@preview

I have to run:

heroku plugins:install salesforce-alm@preview

**Comment by tnoonan-salesforce** [comment]
salesforce-alm is hosted on heroku-npm.herokuapp.com

Additionally, when I list plugins by running (heroku plugins). It doesn’t list the tag name. To me, it seems like it should so users know updates are coming from the named tag not latest.

**Comment by dickeyxxx** [comment]
plugins:update is a command for the ruby plugins, while the documentation isn't clear on this, the command is going to go away along with the rest of the ruby code this month

**Comment by dickeyxxx** [comment]
you can use `heroku update` to update plugins

**Comment by ransombriggs** [comment]
@dickeyxxx this was the issue that we talked about with how `dist-tags` are cached for 24 hours, so `heroku update` appears to not work, but it would after 24 hours.
