### ISSUE TITLE
heroku run -- myapp --help fails

### ISSUE THREAD

**Issue by duane-unitive** [heroku/legacy-cli#2047]
When running a remote command line with `heroku`, the `--help` and `-h` options fail locally without running the remote.

```
$ heroku run --app $app -- myapp --help
 !    myapp is not a heroku command. See `heroku help`.
$ heroku run --app $app -- myapp -h
 !    myapp is not a heroku command. See `heroku help`.
$ heroku run --app $app -- myapp --option
Running myapp --option on ⬢ myserver... connecting, run.9102 (Standard-1X)
```

The `--` option should separate command line options for the sub-command from the command line options for `heroku`.

**Comment by dickeyxxx** [comment]
this is fixed now
