### ISSUE TITLE
Error Running Heroku CLI After Successful Install

### ISSUE THREAD

**Issue by jh0274** [heroku/legacy-cli#2049]
Hi

I followed the instructions to install the Heroku CLI from here

https://devcenter.heroku.com/articles/heroku-cli

I then tried to run 'heroku --version' and i get the following error:

"dyld: Symbol not found: _SecCertificateCopyNormalizedSubjectContent
  Referenced from: /usr/local/bin/heroku
  Expected in: flat namespace

Trace/BPT trap"

Can you help with this please?

**Comment by dickeyxxx** [comment]
are you on snow leopard?

**Comment by jh0274** [comment]
Hi Mac OS 10.5.8.. I think I have found the problem.. CLI only works with 64bit right?

On 21 Jan 2017 10:14 p.m., Jeff Dickey <notifications@github.com> wrote:
are you on snow leopard?

**Comment by dickeyxxx** [comment]
must be 10.7+
