### ISSUE TITLE
Upgrade net-ssh for better Ruby 2.4 support

### ISSUE THREAD

**Issue by mrhead** [heroku/legacy-cli#2053]
This gem depends on `net-ssh` 2.9.2 which produces `constant OpenSSL::Cipher::Cipher is deprecated` warnings. The comment in the gemspec file says that it is locked on this version to preserve Ruby 1.9.3 support.

So in order to support Ruby 2.4 we should get rid of Ruby 1.9.3 support first.

**Comment by dickeyxxx** [comment]
This project is not under current development
