### ISSUE TITLE
issue with heroku login console

### ISSUE THREAD

**Issue by julienwat75** [heroku/legacy-cli#2058]
Hello i ve got issue when i want to connect to my heroku console or heroku login:

!    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       undefined method `[]' for nil:NilClass (NoMethodError)
    Command:     heroku -version
    Version:     heroku-toolbelt/3.43.12 (x86_64-linux) ruby/2.1.10
    Error ID:    27dec6881b544b73b9ee9c9570d3d08f

    More information in /home/julien/.heroku/error.log

I ve never had this before and i change nothing 

Could you help me please ?

Thanks

Julien Waterlot

**Comment by dickeyxxx** [comment]
please reinstall, your CLI is out of date
