### ISSUE TITLE
heroku client broken, throws errors

### ISSUE THREAD

**Issue by agi-eng-innovation** [heroku/legacy-cli#2059]
Last week everything was fine, this week whenever I run Heroku command line client I get the following results:

AGIML-A05567 ~$ heroku --version
/Users/aschulak/.local/share/heroku/client/bin/heroku: fork: Resource temporarily unavailable
/Users/aschulak/.local/share/heroku/client/bin/heroku: line 12: cd: : No such file or directory
/Users/aschulak/.local/share/heroku/client/bin/heroku: line 18: [: /Users/aschulak/.local/share/heroku/client/bin: unary operator expected
/Users/aschulak/.local/share/heroku/client/bin/heroku: line 21: /node: No such file or directory

This is Mac OS X 10.11.4. I have uninstalled and re-installed to no avail. Getting ready to launch project but am now dead in the water. Please advise!

Thanks,
Andrew

**Comment by dickeyxxx** [comment]
As mentioned in the support ticket, your system is likely out of file descriptors. You can verify with `ulimit`. A restart is probably in order.

**Comment by agi-eng-innovation** [comment]
Unfortunately a reboot did not help and I continue to get the same errors.

**Comment by dickeyxxx** [comment]
you could try deleting ~/.local/share/heroku

**Comment by agi-eng-innovation** [comment]
Bingo, thank you!
