### ISSUE TITLE
undefined method `split' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by sonu1989** [heroku/legacy-cli#2062]
Hi Team,

I am facing below issue when I run the command `heroku restart`

`Error:       undefined method `split' for nil:NilClass (NoMethodError)
    Command:     heroku restart
    Version:     heroku-gem/3.41.5 (i686-linux) ruby/2.2.2
    Error ID:    bf37840fdb15491895c50a66b74e2d88
`

Could you help me what us issues.

Thanks you so much in advance for any kind of help.

**Comment by dickeyxxx** [comment]
Please reinstall your CLI

**Comment by sonu1989** [comment]
Thank you! I will install

**Comment by sonu1989** [comment]
Thank you!
