### ISSUE TITLE
Pushing to heroku takes way too long

### ISSUE THREAD

**Issue by dakimaru** [heroku/legacy-cli#362]
I must be pushing files that I should not, but it takes forever to push to heroku. I just used `rails new app`  and changed some files like readme, so shouldnt be that big. Any advise?

`[app (master)]$ git push heroku
Counting objects: 6968, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (6535/6535), done.
Writing objects:   1% (114/6950), 9.29 MiB | 79 KiB/s`

**Comment by Guzim** [comment]
Same for me. Deploy takes forever

**Comment by ransombriggs** [comment]
@Guzim this may be due to an incident right now with the heroku platform (https://status.heroku.com/), I will update this issue once the incident is over so that you can try again.

**Comment by ransombriggs** [comment]
@Guzim could you try your deploy again, the incident appears to have been fully resolved.
