### ISSUE TITLE
SSL_Connect Error

### ISSUE THREAD

**Issue by anilshanbhag** [heroku/legacy-cli#503]
I had a look through the previous threads regarding the same but then my version is updated and I still get the error .

anil-Studio-1558 ~ # heroku login
Enter your Heroku credentials.
Email: anilashanbhag@gmail.com
Password (typing will be hidden): 
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

```
Error:       SSL_connect SYSCALL returned=5 errno=0 state=unknown state (OpenSSL::SSL::SSLError) (Excon::Errors::SocketError)
Backtrace:   /usr/local/heroku/vendor/gems/excon-0.15.5/lib/excon/ssl_socket.rb:82:in `connect'
             /usr/local/heroku/vendor/gems/excon-0.15.5/lib/excon/ssl_socket.rb:82:in `initialize'
             /usr/local/heroku/vendor/gems/excon-0.15.5/lib/excon/connection.rb:344:in `new'
             /usr/local/heroku/vendor/gems/excon-0.15.5/lib/excon/connection.rb:344:in `socket'
             /usr/local/heroku/vendor/gems/excon-0.15.5/lib/excon/connection.rb:175:in `request_kernel'
             /usr/local/heroku/vendor/gems/excon-0.15.5/lib/excon/connection.rb:101:in `request'
             /usr/local/heroku/vendor/gems/heroku-api-0.3.2/lib/heroku/api.rb:60:in `request'
             /usr/local/heroku/vendor/gems/heroku-api-0.3.2/lib/heroku/api/login.rb:9:in `post_login'
             /usr/local/heroku/lib/heroku/auth.rb:76:in `api_key'
             /usr/local/heroku/lib/heroku/auth.rb:185:in `ask_for_credentials'
             /usr/local/heroku/lib/heroku/auth.rb:217:in `ask_for_and_save_credentials'
             /usr/local/heroku/lib/heroku/auth.rb:80:in `get_credentials'
             /usr/local/heroku/lib/heroku/auth.rb:41:in `login'
             /usr/local/heroku/lib/heroku/command/auth.rb:22:in `login'
             /usr/local/heroku/lib/heroku/command.rb:179:in `run'
             /usr/local/heroku/lib/heroku/cli.rb:25:in `start'
             /usr/bin/heroku:26:in `<main>'

Command:     heroku login
HTTP Proxy:  http://username:passwd@proxy:port
HTTPS Proxy: http://username:passwd@proxy:port
Version:     heroku-toolbelt/2.30.2 (x86_64-linux) ruby/1.9.2
```

anil-Studio-1558 ~ # wget https://encrypted.google.com
--2012-08-05 10:44:09--  https://encrypted.google.com/
Resolving netmon.iitb.ac.in... 10.201.13.50
Connecting to netmon.iitb.ac.in|10.201.13.50|:80... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `index.html'

```
[ <=>                                   ] 12,927      --.-K/s   in 0.001s  
```

2012-08-05 10:44:24 (18.0 MB/s) - `index.html' saved [12927]

anil-Studio-1558 ~ # wget http://google.com
--2012-08-05 10:44:32--  http://google.com/
Connecting to 127.0.0.1:3128... connected.
Proxy request sent, awaiting response... 301 Moved Permanently
Location: http://www.google.com/ [following]
--2012-08-05 10:44:32--  http://www.google.com/
Connecting to 127.0.0.1:3128... connected.
Proxy request sent, awaiting response... 302 Moved Temporarily
Location: http://www.google.co.in/ [following]
--2012-08-05 10:44:32--  http://www.google.co.in/
Connecting to 127.0.0.1:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `index.html.1'

```
[ <=>                                   ] 14,230      --.-K/s   in 0.003s  
```

2012-08-05 10:44:32 (4.71 MB/s) - `index.html.1' saved [14230]

anil-Studio-1558 ~ # heroku version
heroku-toolbelt/2.30.2 (x86_64-linux) ruby/1.9.2

**Comment by 108anup** [comment]
Version:     heroku-toolbelt/3.42.31 (x86_64-linux) ruby/1.9.3
giving similar error (behind proxy)

heroku-cli: Installing Toolbelt v4...SSL_connect returned=1 errno=0 state=unknown state: unknown protocol (OpenSSL::SSL::SSLError)
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/ssl_socket.rb:120:in `connect_nonblock'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/ssl_socket.rb:120:in `initialize'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:387:in `new'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:387:in `socket'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:106:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/mock.rb:47:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/instrumentor.rb:22:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/middlewares/base.rb:15:in `request_call'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon/connection.rb:233:in `request'
/usr/local/heroku/vendor/gems/excon-0.45.4/lib/excon.rb:229:in `get'
/usr/local/heroku/lib/heroku/jsplugin.rb:210:in `manifest'
/usr/local/heroku/lib/heroku/jsplugin.rb:223:in `url'
/usr/local/heroku/lib/heroku/jsplugin.rb:139:in `setup'
/usr/local/heroku/lib/heroku/cli.rb:27:in `start'
/usr/local/heroku/bin/heroku:25:in `<main>'
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       SSL_connect returned=1 errno=0 state=unknown state: unknown protocol (OpenSSL::SSL::SSLError) (Excon::Errors::SocketError)
    Command:     heroku 
    HTTP Proxy:  http://username:pass@host:port/
    HTTPS Proxy: https://username:pass@host:port/
    Version:     heroku-toolbelt/3.42.31 (x86_64-linux) ruby/1.9.3
