### ISSUE TITLE
Cannot connect to postgresql database

### ISSUE THREAD

**Issue by iamvery** [heroku/legacy-cli#507]
I am attempting to migrate the database of a new app today with little luck. The command reports that the operation timed out in connecting to the database.

Also, running:

```
heroku pg:psql
```

is resulting in the following error.

```
psql: could not connect to server: Operation timed out
        Is the server running on host "ec2-107-22-170-43.compute-1.amazonaws.com" (107.22.170.43) and accepting
        TCP/IP connections on port 5432?
```

According to the status site there are no known outages, but I am also not able to access `pg:psql` from an existing app successfully. I initially suspected this may be related to the shared-database -> postgresql migrations that are going on today, but I also found this (http://stackoverflow.com/questions/11695497/mountain-lion-heroku-update-gives-weird-error-message) discussion that lead me to believe it could be related to Mountain Lion.

Help?

**Comment by FaroukY** [comment]
Thank you iamvery for mentioning your solution. Turns out I had the same problem and my school's network was blocking it. Very helpful.
