### ISSUE TITLE
Add support to recompile slug without a push or config change

### ISSUE THREAD

**Issue by NeoPhi** [heroku/legacy-cli#514]
Using cedar with a node.js package if you don't specify explicit versions in a package.json and a referenced project is updated in order to get the slug to recompile you have to push a change. In most cases I don't want to have to make a code change but instead just want to recompile the slug so it pulls down the latest version of packages referenced via package.json. Adding support for this would be handy.

**Comment by agconti** [comment]
+1 for heroku recompile.  Using and empty commit works: 
```
git commit --allow-empty -m "empty commit"
git push heroku master
```
But it creates an unnecessarily dirty commit history.

**Comment by csuhta** [comment]
@agconti You can now use this to rebuild without creating commits: https://github.com/heroku/heroku-repo

**Comment by damienfa** [comment]
@csuhta ... heroku/heroku-repo do not have a "rebuild" command ? What is your point ?

**Comment by csuhta** [comment]
@damienfa `heroku-repo` lets you blow out your Heroku buildpack caches and Git remote. So one of the ways you can rebuild/recompile your application without making any new Git commits is:

```shell
heroku plugins:install https://github.com/heroku/heroku-repo.git
cd your-app
heroku repo:purge_cache
heroku repo:reset
git push heroku master
```

**Comment by hernanvicente** [comment]
+1 for implementing it. @csuhta your approach worked perfectly for me. Thanks!
