### ISSUE TITLE
Heroku client internal error when creating App

### ISSUE THREAD

**Issue by clickpoint** [heroku/legacy-cli#535]
I encountered the following problem when attempting to create a new App. Any ideas on what could have caused the problem? Thanks.

C:\project>heroku create clickpointau --stack cedar
Creating clickpointau... done, stack is cedar
http://clickpointau.herokuapp.com/ | git@heroku.com:clickpointau.git
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

```
Error:       No such file or directory -  git remote 2>&1  (Errno::ENOENT)
Backtrace:   C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:112:in ``'
             C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:112:in `git'
             C:/Program Files (x86)/Heroku/lib/heroku/helpers.rb:152:in `create_git_remote'
             C:/Program Files (x86)/Heroku/lib/heroku/command/apps.rb:213:in `create'
             C:/Program Files (x86)/Heroku/lib/heroku/command.rb:193:in `run'
             C:/Program Files (x86)/Heroku/lib/heroku/cli.rb:28:in `start'
             C:/Program Files (x86)/Heroku/bin/heroku:23:in `<main>'

Command:     heroku create clickpointau --stack cedar
Version:     heroku-toolbelt/2.30.5 (i386-mingw32) ruby/1.9.2
```

**Comment by jeffreytu** [comment]
Hello. I just came across this issue today while trying to `heroku create`. Other commands like `apps` and `config` give me the same:

```
$ heroku create
Error submitting error.
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

    Error:       No such file or directory -  git remote -v 2>&1  (Errno::ENOENT)
    Command:     heroku create
    Plugins:     heroku-push
    Version:     heroku/toolbelt/3.25.0 (i386-mingw32) ruby/1.9.3


    More information in c:/Users/Jstadragon/.heroku/error.log
```
I'm on Windows 7 with an updated heroku-belt and have tried the same commands in cmd and git bash, but still get the same error.

**Comment by dickeyxxx** [comment]
@jeffreytu does git work? what's the output of `git --version`?

**Comment by jeffreytu** [comment]
```
$ git --version
git version 1.9.5.msysgit.0
```

**Comment by Thuruv** [comment]
$ git --version
git version 1.9.4.msysgit.2

Same Here. . Please help. .

**Comment by andrelindquist** [comment]
git --version
git version 1.9.5msysgit.0

Anyone find a way to get through this?
