### ISSUE TITLE
SSH Forward Agent not working

### ISSUE THREAD

**Issue by andhapp** [heroku/legacy-cli#546]
I am trying to deploy a private gem (hosted on github) as part of my rails application on Heroku (Cedar stack), but for some reason it fails with :

<pre>
Permission denied (publickey).
</pre>

I've already tried using ForwardAgent in my .ssh/config, like this:

<pre>
Host heroku.com
     ForwardAgent yes
</pre>

and it still doesn't work. As it's hosted on github, I'm using the git url: 

<pre>
git@github.com:&lt;my-account&gt;/&lt;my-repository&gt;.git
</pre>

Is there a workaround apart from adding the username/password and using http basic auth?

**Comment by EiNSTeiN-** [comment]
I am having this problem, too. Private dependency management is a big pain in the butt on heroku.

**Comment by dickeyxxx** [comment]
the best solution is probably `bundle package --all`
