### ISSUE TITLE
The HEROKU_API_KEY environment variable breaks auth commands.

### ISSUE THREAD

**Issue by zeke** [heroku/legacy-cli#572]
This issue only affects a small slice of users, but I figured I should log it anyway. If you keep your `HEROKU_API_KEY` in `ENV`, you cannot switch accounts using the CLI, and `heroku auth:whoami` doesn't work.

**Comment by trimble** [comment]
Reading through this one was a fun trip through the past...but it can probably be closed now...maybe?

/cc @dickeyxxx
