### ISSUE TITLE
when i login in heroku comand prompt ,i am getting so many error like:

### ISSUE THREAD

**Issue by dpjiitkgp** [heroku/legacy-cli#642]
when i login in heroku comand prompt ,i am getting so many error like:
!heroku client internal error
Error: No connection could be made beacuse the target machine actively refused it.-connect(2) (Error::ECONNERFUSED)(Excon::error::SoketError)

**Comment by gsanjeevkumar** [comment]
this is not working for me
I am using Mac ruby/1.9.3
