### ISSUE TITLE
Unable to run "heroku run" via proxy

### ISSUE THREAD

**Issue by rinrinne** [heroku/legacy-cli#658]
> $ heroku run rake db:migrate
> Running `rake db:migrate` attached to terminal... up, run.1003
>  !    Heroku client internal error.
>  !    Search for help at: https://help.heroku.com
>  !    Or report a bug at: https://github.com/heroku/heroku/issues/new
> 
> ```
> Error:       No route to host - connect(2) (Errno::EHOSTUNREACH)
> Backtrace:   /usr/local/heroku/lib/heroku/client/rendezvous.rb:39:in `initialize'
>              /usr/local/heroku/lib/heroku/client/rendezvous.rb:39:in `open'
>              /usr/local/heroku/lib/heroku/client/rendezvous.rb:39:in `block in start'
>              /usr/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
>              /usr/local/heroku/lib/heroku/client/rendezvous.rb:31:in `start'
>              /usr/local/heroku/lib/heroku/command/run.rb:125:in `rendezvous_session'
>              /usr/local/heroku/lib/heroku/command/run.rb:112:in `run_attached'
>              /usr/local/heroku/lib/heroku/command/run.rb:21:in `index'
>              /usr/local/heroku/lib/heroku/command.rb:207:in `run'
>              /usr/local/heroku/lib/heroku/cli.rb:28:in `start'
>              /usr/local/heroku/bin/heroku:25:in `<main>'
> 
> Command:     heroku run rake db:migrate
> HTTP Proxy:  http://localhost:8080/
> HTTPS Proxy: https://localhost:8080/
> Version:     heroku-toolbelt/2.33.5 (x86_64-linux) ruby/1.9.3
> ```

I have a reverse proxy on my PC.

**Comment by GoncaloPT** [comment]
As mentioned before, this workaround doesn't work with useful commands like heroku run bash :(

**Comment by ransombriggs** [comment]
@GoncaloPT do you connect through a SOCKS proxy?
