### ISSUE TITLE
Heroku client internal error 

### ISSUE THREAD

**Issue by dbend** [heroku/legacy-cli#664]
Just trying to simply login to heroku on the command line and create an app.  When typing "heroku login" on the command line, I'm asked for my email and password, and then I get the error below.  I have installed the Heroku Toolbelt and I'm using a mac osx 10.8.2.  I also noticed that I am unable to access these 2 pages on Heroku in my browser:  https://api.heroku.com/login and https://help.heroku.com/.  I'm sure it's a simple problem, but any help would be greatly appreciated.  Thanks.

$ heroku login
Enter your Heroku credentials.
Email: xxxxx
Password (typing will be hidden): 
 !    Heroku client internal error.
 !    Search for help at: https://help.heroku.com
 !    Or report a bug at: https://github.com/heroku/heroku/issues/new

```
Error:       Connection refused - connect(2) (Errno::ECONNREFUSED) (Excon::Errors::SocketError)
Backtrace:   /usr/local/heroku/vendor/gems/excon-0.16.10/lib/excon/socket.rb:41:in `connect'
             /usr/local/heroku/vendor/gems/excon-0.16.10/lib/excon/socket.rb:41:in `block (2 levels) in connect'
             /usr/local/heroku/ruby/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
             /usr/local/heroku/vendor/gems/excon-0.16.10/lib/excon/socket.rb:40:in `block in connect'
             /usr/local/heroku/vendor/gems/excon-0.16.10/lib/excon/socket.rb:29:in `each'
             /usr/local/heroku/vendor/gems/excon-0.16.10/lib/excon/socket.rb:29:in `connect'
             /usr/local/heroku/vendor/gems/excon-0.16.10/lib/excon/ssl_socket.rb:77:in `connect'
             /usr/local/heroku/vendor/gems/excon-0.16.10/lib/excon/socket.rb:16:in `initialize'
             /usr/local/heroku/vendor/gems/excon-0.16.10/lib/excon/ssl_socket.rb:8:in `initialize'
             /usr/local/heroku/vendor/gems/excon-0.16.10/lib/excon/connection.rb:364:in `new'
             /usr/local/heroku/vendor/gems/excon-0.16.10/lib/excon/connection.rb:364:in `socket'
             /usr/local/heroku/vendor/gems/excon-0.16.10/lib/excon/connection.rb:192:in `request_kernel'
             /usr/local/heroku/vendor/gems/excon-0.16.10/lib/excon/connection.rb:103:in `request'
             /usr/local/heroku/vendor/gems/heroku-api-0.3.7/lib/heroku/api.rb:74:in `request'
             /usr/local/heroku/vendor/gems/heroku-api-0.3.7/lib/heroku/api/login.rb:9:in `post_login'
             /usr/local/heroku/lib/heroku/auth.rb:80:in `api_key'
             /usr/local/heroku/lib/heroku/auth.rb:189:in `ask_for_credentials'
             /usr/local/heroku/lib/heroku/auth.rb:221:in `ask_for_and_save_credentials'
             /usr/local/heroku/lib/heroku/auth.rb:84:in `get_credentials'
             /usr/local/heroku/lib/heroku/auth.rb:41:in `login'
             /usr/local/heroku/lib/heroku/command/auth.rb:31:in `login'
             /usr/local/heroku/lib/heroku/command.rb:207:in `run'
             /usr/local/heroku/lib/heroku/cli.rb:28:in `start'
             /usr/bin/heroku:24:in `<main>'

Command:     heroku login
Version:     heroku-toolbelt/2.33.5 (x86_64-darwin10.8.0) ruby/1.9.3
```

**Comment by gsanjeevkumar** [comment]
Error:       Connection refused - connect(2) (Errno::ECONNREFUSED) (Excon::Errors::SocketError)
Command:     heroku login
Version:     heroku-toolbelt/3.42.20 (x86_64-darwin10.8.0) ruby/1.9.3

Let you know if you guys can help please...

**Comment by ransombriggs** [comment]
@gsanjeevkumar are you able to visit https://api.heroku.com/login ?  It sounds like the user that previously reported this issue may have had network problems.

**Comment by gsanjeevkumar** [comment]
@ransombriggs I can login to the URL you sent. what are the settings for the network are necessary/required i am behind a fire-wall.

Thanks in advance.

**Comment by ransombriggs** [comment]
Export HTTP_PROXY and HTTPS_PROXY then try again.

**Comment by ransombriggs** [comment]
@gsanjeevkumar ^^^ (just making sure you get notified)
