### ISSUE TITLE
Feature request: `heroku fork` should copy the git repo

### ISSUE THREAD

**Issue by twe4ked** [heroku/legacy-cli#748]
After a short discussion on a [support ticket](https://help.heroku.com/tickets/81604) @friism suggested I open an issue here.

From the ticket:

> I noticed that it doesn't copy the git repo to the new app so if I manually push to the forked app I need to re-push the entire repo. This is a problem with our ~100mb repo. Any chance you could make it copy the repo across?

**Comment by Xplouder** [comment]
+1

**Comment by dickeyxxx** [comment]
I realize the first comment here suggested that the conversation move to this github repo, but today this repo is only monitored by the CLI team and this change would involve other teams. So if you want it, I'd ask for you to submit a support ticket.

**Comment by thiagovsk** [comment]
+1

**Comment by brickgale** [comment]
+1

**Comment by Narvey** [comment]
Has anyone made a ticket for this yet? +1's don't do much good if this will not be seen by the correct team.

**Comment by zeke** [comment]
`heroku fork` is not a supported thing any more. Consider using [review apps](https://devcenter.heroku.com/articles/github-integration-review-apps) instead.

> Review apps run the code in any GitHub pull request in a complete, disposable app on Heroku. Each review app has a unique URL you can share. You can configure review apps to spin up automatically for each pull request, or create each manually at the push of a button from the Heroku Pipelines page of the connected repo.

**Comment by dickeyxxx** [comment]
closing as fork is deprecated
