### ISSUE TITLE
Requested API endpoint was not found

### ISSUE THREAD

**Issue by omarshammas** [heroku/legacy-cli#972]
I'm trying to update the ssl certificates for an app running on the `bamboo-ree-1.8.7` stack. When running `heroku certs` I encounter the error:

```
 !    The requested API endpoint was not found. Are you using the right HTTP verb (i.e. `GET` vs. `POST`), and did you specify your intended version with the `Accept` header?
```

**Comment by Hanamant-Kadlimatti** [comment]
The requested API endpoint was not found. Are you using the right HTTP verb (i.e. `GET` vs. `POST`), and did you specify your intended version with the `Accept` header?

Hi Iam getting above error.
My heroku version is
heroku/toolbelt/3.43.5 (i386-mingw32) ruby/2.1.7
heroku-cli/5.2.23-0daa80b (windows-386) go1.6.2
 
help me

**Comment by ransombriggs** [comment]
@Hanamant-Kadlimatti what command are you trying to run?

**Comment by abdul-baseer** [comment]
The requested API endpoint was not found. Are you using the right HTTP verb (i.e. GET vs. POST), and did you specify your intended version with the Accept header?

I am getting above error too while creating a heroku remote
